HCM_DISTRICTS = [
    'quan 1 ho chi minh',
    'quan 2 ho chi minh',
    'quan 3 ho chi minh',
    'quan 4 ho chi minh',
    'quan 5 ho chi minh',
    'quan 6 ho chi minh',
    'quan 7 ho chi minh',
    'quan 8 ho chi minh',
    'quan 9 ho chi minh',
    'quan 10 ho chi minh',
    'quan 11 ho chi minh',
    'quan 12 ho chi minh',
    'quan thu duc ho chi minh',
    'quan binh tan ho chi minh',
    'quan tan binh ho chi minh',
    'quan binh thanh ho chi minh',
    'quan tan phu ho chi minh',
    'quan go vap ho chi minh',
    'quan phu nhuan ho chi minh',
    'huyen binh chanh ho chi minh',
    'huyen hoc mon ho chi minh',
    'huyen can gio ho chi minh',
    'huyen cu chi ho chi minh',
    'huyen nha be ho chi minh'
]